### PR TITLE
Fix hostile S’pht’Kr guided bolts in chapter 3 early levels; Flight of Icarus and Pfhor får lamm revisions; hopefully merged changes so this one can be resolved more easily

### PR DESCRIPTION
**Pull request by aaronfreed**
I still don’t know if this will work because Github’s interface is really finicky, but here’s hoping

### CODE REVIEW

**Comment by Pfhorrest** [comment]
This PR tells me it has no conflicts with the base branch and merging can be performed automatically, but when I click for it to do so it says it can’t automatically merge it. I’ll look into it more tomorrow night.

**Comment by aaronfreed** [comment]
I don't understand what the hell is going on with this because it's giving
me the exact same message. I suspect the solution is probably going to be
for one of us to give the other one access to the other's branch, but I
haven't the faintest idea how. Lia didn't seem to understand either.

**Comment by ravenshining** [comment]
I think, because you made your changes to Flight of Icarus *before* actually pulling it in to your own branch, git thinks you have independently created Flight of Icarus.  Two possibilities I can think of here: 1.) as I've said several times on the Pfhorums, you need to update your own branch so it is up to date with Pfhorrest's.  Currently it is 12 commits behind.  Do that by submitting a PR to YOURSELF, based off Pfhorrest's.  2)  your history may be so messed up that you need to back up and either rebase or start again.

**Comment by Pfhorrest** [comment]
Yeah something is really messed up here, and I think Lia's advice sounds good. I was going to try to merge this minus whatever conflicted, by merging my master into the PR14 fork and then accepting PR14 back into master, like I did last time, but I can't even get GitHub desktop to switch to the PR14 work because of something weird going on with Pfhor Får Lamm. (It insists that I remove the file from the working tree before it can switch branches, but even when I do that, it gives me the same error and re-creates the file in the process. I wonder if in that case it might be the å character confusing it somehow?)

**Comment by Pfhorrest** [comment]
I see looking in Aaron's fork that he made a pull request from my fork, but that that pull request has not been accepted, probably because it can't be automatically merged, probably for the same reason I can't automatically merge the PRs in the other direction.

Aaron I think the only solution at this point is to back up your version of the maps folder somewhere else that git isn't watching, and start over from scratch with a new fork of my master. Then overwrite your fork of my master with your backed-up changed files, commit those changes to git, and send a new PR to me.

Then in the future, before making any further changes to your fork, pull the current version of my master into it, and that should avoid this problem happening again.

**Comment by aaronfreed** [comment]
Yes, I think Pfhorrest is correct - unless there's some way to give each
other access to the other's fork that I'm not aware of, the easiest
(possibly only) solution is going to be to just make another fork. Thanks
to both of you for the info, though. I had no idea manually moving my
version over the way I did was going to cause such an inconvenience. I'm
just not 100% sure I understand how to avoid a recurrence of the problem -
I hope the last sentence is correct. What a pain.

**Comment by ravenshining** [comment]
Well, you should have write access to your own fork, and be able to resolve things there before going and making this PR here.

Definitely doing things "manually" is anti-git.  Let git do all the forking, cloning, pushing, pulling, etc., and you should be fine.  Remember git's primary purpose is to record history, not to store files, even if storing files is what we actually use it for.

I know it's a pain.  I only stared using git because all my favourite things use it and wanted to learn.  It's a steep curve, but once you get that "git records history" paradigm straight it gets smoother.

**Comment by Pfhorrest** [comment]
closed because this PR is old and obsolete now

**Pull request closed without merging**
